In [1]:
import numpy as np

In [2]:
# reward matrix

R = np.matrix([[-1,-1,-1,-1,0,-1],
               [-1,-1,-1,0,-1,100],
               [-1,-1,-1,0,-1,-1],
               [-1,0,0,-1,0,-1],
               [-1,0,0,-1,-1,100],
               [-1,0,-1,-1,0,100]])

In [4]:
# Q-matrix

Q = np.matrix(np.zeros([6,6]))

In [5]:
print(Q)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [6]:
# gamma_learning rate

gamma = 0.8

In [7]:
# initial state

initial_state = 1

In [8]:
# function to return all the available actions in the state given as an argument

In [16]:
def available_actions(state) :
    current_state_row = R[state,]
    av_act = np.where(current_state_row >= 0)[1]
    return av_act

In [17]:
available_act = available_actions(initial_state)

In [18]:
print(available_act)

[3 5]


In [19]:
def sample_next_actions(available_act) :
    next_action = int(np.random.choice(available_act, 1))
    return next_action

In [21]:
action = sample_next_actions(available_act)

In [22]:
print(action)

3


In [57]:
def update(current_state, action, gamma):
    max_index = np.where(Q[action] == np.max(Q[action,])) [1]
    if max_index.shape[0] >1:
        max_index = int(np.random.choice(max_index, size = 1))
    else:
        max_index = int(max_index)
        
    max_value = Q[action,max_index] 
     
    # q learning formula

    Q[current_state,action] = R[current_state,action] + gamma * max_value

In [58]:
update(initial_state, action, gamma)

In [59]:
# train - for 10000 times

for i in range(10000):
    current_state = np.random.randint(0,int(Q.shape[0]))
    available_act = available_actions(current_state)
    action = sample_next_actions(available_act)
    update(current_state, action, gamma)

In [60]:
print(Q)

[[   0.    0.    0.    0.  900.    0.]
 [   0.    0.    0.  810.   -1. 1000.]
 [   0.    0.    0.  810.    0.    0.]
 [   0.  900.  729.    0.  900.    0.]
 [   0.  900.  729.    0.    0. 1000.]
 [   0.  900.    0.    0.  900. 1000.]]


In [61]:
print(Q/np.max(Q)*100)

[[  0.    0.    0.    0.   90.    0. ]
 [  0.    0.    0.   81.   -0.1 100. ]
 [  0.    0.    0.   81.    0.    0. ]
 [  0.   90.   72.9   0.   90.    0. ]
 [  0.   90.   72.9   0.    0.  100. ]
 [  0.   90.    0.    0.   90.  100. ]]


In [62]:
#test

current_state = 2
steps = [current_state]

In [ ]:
while current_state != 5:
    next_step_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[1]
    if next_step_index.shape[0] >1:
        next_step_index = int(np.random.choice(next_step_index, size=1))
    else :
        next_step_index = int(next_step_index)

In [ ]:
steps.append(next_step_index)
current_state = next_step_index

In [ ]:
print("path: \n",steps)